version: '3.8'

services:
  axon-server:
    image: axoniq/axonserver:2023.2.1-jdk-17
    hostname: axonserver
    networks:
      - ddd-axon-demo
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    volumes:
      - ./data:/axonserver/data
      - ./axon-config:/axonserver/config
      - ./events:/axonserver/events

networks:
  ddd-axon-demo: